version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - server

  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_app
